import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trending",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyClass = `${geistSans.variable} ${geistMono.variable}`;

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>

      <body
        style={{ background: "magenta" }}
        className={bodyClass + " layout-root"}
      >
        <div
          style={{
            padding: 20,
            textAlign: "center",
            color: "white",
            fontSize: 28,
            fontWeight: 800,
          }}
        >
          LAYOUT.TSX IS ACTIVE — MAGENTA TEST
        </div>

        <header className="app-header">
          <div className="app-header-inner">
            <h1>Trending Repos</h1>
          </div>
        </header>

        <main className="app-main">{children}</main>

        <footer className="app-footer" role="contentinfo">
          <nav className="footer-nav" aria-label="Primary">
            <button className="footer-btn active">
              <span className="icon">★</span>
              <span className="label">Trending</span>
            </button>
            <button className="footer-btn">
              <span className="icon">⚙️</span>
              <span className="label">Settings</span>
            </button>
          </nav>
        </footer>
      </body>
    </html>
  );
}
